<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Voters - {{ $votingExclusive->id ?? 'N/A' }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { color: #2563eb; margin: 0; font-size: 22px; }
        .meta { margin-bottom: 12px; color: #64748b; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 8px; border: 1px solid #e2e8f0; font-size: 13px; text-align: left; }
        th { background: #f1f5f9; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; color: #64748b; font-size: 12px; }
        .no-data { padding: 20px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; text-align: center; color: #64748b; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Student Voters Report</h1>
        <div class="meta">
            @php
                $veId = $votingExclusive->id ?? null;
                $veDeptName = optional($votingExclusive->department)->department_name ?? null;
                $start = $votingExclusive->start_datetime ? \Carbon\Carbon::parse($votingExclusive->start_datetime)->format('M d, Y h:i A') : null;
                $end = $votingExclusive->end_datetime ? \Carbon\Carbon::parse($votingExclusive->end_datetime)->format('M d, Y h:i A') : null;
            @endphp
            <div>
                <strong>Voting Exclusive:</strong>
                @if($veDeptName) {{ $veDeptName }}@endif
            </div>
            <div><strong>Period:</strong> {{ $start ?: '-' }} - {{ $end ?: '-' }}</div>
            <div><strong>Generated on:</strong> {{ date('F d, Y \a\t h:i A') }}</div>
        </div>
    </div>

    @if(!empty($voters) && count($voters) > 0)
        <table>
            <thead>
                <tr>
                    <th style="width:6%">#</th>
                    <th style="width:30%">Student Name</th>
                    <th style="width:14%">Student ID</th>
                    <th style="width:20%">Course</th>
                    <th style="width:20%">Department</th>
                    <th style="width:18%">Voted At</th>
                </tr>
            </thead>
            <tbody>
                @foreach($voters as $i => $vote)
                    @php
                        $student = $vote->student;
                        $fullName = trim(sprintf('%s %s %s %s', $student->first_name ?? '', $student->middle_name ?? '', $student->last_name ?? '', $student->suffix ?? ''));
                    @endphp
                    <tr>
                        <td>{{ $i + 1 }}</td>
                        <td>{{ $fullName }}</td>
                        <td>{{ $student->student_id ?? '' }}</td>
                        <td>{{ optional($student->course)->course_name ?? 'N/A' }}</td>
                        <td>{{ optional($student->department)->department_name ?? '' }}</td>
                        <td>{{ \Carbon\Carbon::parse($vote->created_at ?? $vote->updated_at)->format('M d, Y h:i A') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No voters found for this voting exclusive.</div>
    @endif

    <div class="footer">Generated by stii-evote on {{ date('F d, Y \a\t h:i A') }}</div>
</body>
</html>
